techapp/urls.py
from django.urls import path
from . import views

app_name = 'techapp'

urlpatterns = [
  path('', views.IndexView.as_view(), name='index'),
  path('search', views.Search, name='search'),
]

techpit/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('techapp.urls')),
]

techapp/models.py
from django.db import models

class Category(models.Model):
  category_l = models.CharField("業態カテゴリ", max_length=10, blank=False)
  name = models.CharField("業態名", max_length=30, blank=False)

  def __str__(self):
    return str(self.name)

class Pref(models.Model):
  pref = models.CharField("都道府県コード", max_length=6, blank=False)
  name = models.CharField("都道府県名", max_length=10, blank=False)

  def __str__(self):
    return str(self.name)

techapp/views.py
from django.shortcuts import render, redirect

from django.views.generic import CreateView, ListView, UpdateView, DetailView, TemplateView

class IndexView(TemplateView):
  template_name = 'techapp/index.html'

def Search(request):
    params = {
    }
    return render (request, 'techapp/index.html', params)

techapp/templates/techapp/index.html
{% load static %}

<!doctype html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="{% static 'js/index.js' %}"></script>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">

</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-right">
      <a class="navbar-brand" href="{% url 'techapp:index' %}">食べナビ</a>
        <div class="collapse navbar-collapse navbar-right" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li>
              <a class="nav-item nav-link" href="">ログアウト</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-item nav-link" href="">ログイン</a>
            </li>
            <li>
              <a class="nav-item nav-link" href="">新規ユーザ登録</a>
            </li>
            {% endif %}
          </ul>
      </div>
    </nav>

    <section class="search">
      <div id="top_carousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'image/topimage1.jpg' %}" class="d-block w-100" height="500px" alt="今日はどこで食べようか？">
            <div class="carousel-caption" style="top:50px">
              <h1><br>今日はどこで食事しよう？</h1>
            </div>
          </div>
          <div class="carousel-item">
            <img src="{% static 'image/topimage2.jpg' %}" class="d-block w-100" height="500px">
            <div class="carousel-caption" style="top:50px">
              <h1><br>リアルな口コミNo.1！</h1>
            </div>
          </div>
          <div class="carousel-item">
            <img src="{% static 'image/topimage3.jpg' %}" class="d-block w-100" height="500px">
            <div class="carousel-caption" style="top:50px">
              <h1><br>行きたいお店の<br>リアルな評判は？</h1>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#top_carousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#top_carousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </section>

    <section class="search-sec">
      <div class="container">
        <form method="GET" action="{% url 'techapp:search' %}" name="searchform">
          <div class="row">
            <div class="col-lg-12">
              <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                  <select class="form-control search-slt" name="pref">
                    <option value="">都道府県</option>
                    {% for item in pref_list %}
                    <option value="{{item.pref}}">{{ item.name }}</option>
                    {% endfor %}
                  </select>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                  <select class="form-control search-slt" name="category_l">
                    <option value="">カテゴリ</option>
                    {% for item in category_list %}
                    <option value="{{item.category_l}}">{{ item.name }}</option>
                    {% endfor %}
                  </select>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                  <input class="form-control search-slt" type="text" placeholder="フリーワード" aria-label="Search" name="freeword">
                </div>
                <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                  <button type="submit" class="btn search-btn">検索</button>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </section>

    <br><br>
    <!-- フッター -->
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <br/><br/>
          <hr/>
          <p>tabenavi</p>
          <a href="https://api.gnavi.co.jp/api/scope/" target="_blank">
            <img src="https://api.gnavi.co.jp/api/img/credit/api_265_65.gif" width="265" height="65" border="0" alt="グルメ情報検索サイト　ぐるなび">
          </a>
          <br/><br/>
        </div>
      </div>
    </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>